### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by stuartfehr** [Dica-Developer/vim-jdb#9]
Love the project. Have been using it for a few days, and made a couple tweaks that I would like to patch. However, my employer does not like contributions to projects which have no license.

They are happy with any of the following licenses: Apache 2, MIT, BSD, GPL, LGPL, Eclipse Public License, MPL, ISC, CC-BY, OFL, MS-PL, or Boost Software License. So, if you could add one of those licenses to this project it would greatly help.

Thanks!

**Comment by mschaaf** [comment]
Hej, thanks for the issue. I will put it officially under the GPL. Please take into account for your contributions to make them in small chunks. And one pull request per feature/bug fix.

**Comment by mschaaf** [comment]
It is now officially under GPL3. Thanks again and I am happy to review your pull requests.
